development:
  :address: mailcatcher
  :port: 1025
  :domain: devsmap.local

test:
  :address: mailcatcher
  :port: 1025
  :domain: devsmap.local

production:
  :address: smtp.sendgrid.net
  :port: 587
  :user_name: apikey
  :password: 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
  :authentication: plain
  :enable_starttls_auto: true
